//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFlurl.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientFlurl.Tests.Resources.MockJson", typeof(MockJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;cep&quot;: &quot;24740-500&quot;,
        ///  &quot;logradouro&quot;: &quot;Rua Libanio Ratazi&quot;,
        ///  &quot;complemento&quot;: &quot;&quot;,
        ///  &quot;bairro&quot;: &quot;Coelho&quot;,
        ///  &quot;localidade&quot;: &quot;São Gonçalo&quot;,
        ///  &quot;uf&quot;: &quot;RJ&quot;,
        ///  &quot;ibge&quot;: &quot;3304904&quot;,
        ///  &quot;gia&quot;: &quot;&quot;,
        ///  &quot;ddd&quot;: &quot;21&quot;,
        ///  &quot;siafi&quot;: &quot;5897&quot;
        ///}.
        /// </summary>
        internal static string Address_correct {
            get {
                return ResourceManager.GetString("Address_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;cep&quot;: &quot;24740-500&quot;,
        ///  &quot;logradouro&quot;: &quot;Rua Libanio&quot;,
        ///  &quot;complemento&quot;: &quot;&quot;,
        ///  &quot;bairro&quot;: &quot;Coelho&quot;,
        ///  &quot;localidade&quot;: &quot;São Gonçalo&quot;,
        ///  &quot;uf&quot;: &quot;&quot;,
        ///  &quot;ibge&quot;: &quot;3304904&quot;,
        ///  &quot;gia&quot;: &quot;&quot;,
        ///  &quot;ddd&quot;: &quot;21&quot;,
        ///  &quot;siafi&quot;: &quot;5897&quot;
        ///}.
        /// </summary>
        internal static string Address_incorrect {
            get {
                return ResourceManager.GetString("Address_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;zipCode&quot;: null,
        ///  &quot;publicPlace&quot;: null,
        ///  &quot;complement&quot;: null,
        ///  &quot;district&quot;: null,
        ///  &quot;location&quot;: null,
        ///  &quot;federativeUnit&quot;: null,
        ///  &quot;ibge&quot;: null,
        ///  &quot;gia&quot;: null,
        ///  &quot;ddd&quot;: null,
        ///  &quot;siafi&quot;: null
        ///}.
        /// </summary>
        internal static string Address_invalid {
            get {
                return ResourceManager.GetString("Address_invalid", resourceCulture);
            }
        }
    }
}
